import { Category, Project } from './types';
import React from 'react';

export const CATEGORY_TRANSLATIONS: Record<string, string> = {
  [Category.AI]: '人工智能',
  [Category.APP]: '应用',
  [Category.TOOL]: '工具',
  [Category.WEBSITE]: '网站',
  [Category.MEDIA]: '媒体',
  [Category.SAAS]: 'SaaS',
  [Category.IOS]: 'iOS',
  [Category.EDUCATION]: '教育',
  [Category.FINANCE]: '金融',
  [Category.SERVICE]: '服务',
  [Category.GAME]: '游戏',
  [Category.NEWSLETTER]: '周刊/通讯',
  [Category.HEALTH]: '健康',
  [Category.DESIGN]: '设计',
  [Category.DEVTOOLS]: '开发者工具',
  [Category.EXTENSION]: '浏览器扩展',
  [Category.API]: 'API',
  [Category.ECOMMERCE]: '电商',
  [Category.ANDROID]: '安卓',
  [Category.SLACK]: 'Slack',
  [Category.ART]: '艺术',
  [Category.DATABASE]: '数据库',
  'All': '全部'
};

export const UI_TRANSLATIONS = {
  zh: {
    heroTitle: '月收入超过 $500 的项目',
    heroSubtitle: '实时分析 Hacker News 帖子，挖掘那些通过 Side Project 实现 $500+ 月收入的精彩案例。',
    dataSource: '数据源',
    connecting: '正在连接 Hacker News...',
    fetching: (count: number) => `正在抓取 ${count} 条评论数据...`,
    fetchingProgress: (curr: number, total: number) => `已获取 ${curr} / ${total} 条评论...`,
    analyzing: '正在解析项目信息...',
    localMode: '本地快速解析模式',
    noProjects: '未找到符合条件的项目',
    noProjectsSub: '可能是数据源暂时无法访问。',
    backToList: '返回项目列表',
    visitProject: '访问项目',
    viewDiscussion: '查看 HN 讨论',
    websitePreview: '网站预览',
    previewNote: '*部分网站可能因安全策略（X-Frame-Options）无法在预览框中加载，请点击上方“访问项目”直接跳转。',
    noPreview: '暂无预览链接',
    filterByTag: '按标签筛选',
    viewDetails: '查看详情',
    view: '查看',
    footerShowing: (current: number, total: number) => `显示 ${current} / ${total} 个项目`,
    footerSource: '数据来源',
    viewModeSnapshot: '网页快照',
    viewModeLive: '实时预览'
  },
  en: {
    heroTitle: 'Projects with $500+ MRR',
    heroSubtitle: 'Real-time analysis of Hacker News threads to discover side projects making $500+ monthly revenue.',
    dataSource: 'Data Source',
    connecting: 'Connecting to Hacker News...',
    fetching: (count: number) => `Fetching ${count} comments...`,
    fetchingProgress: (curr: number, total: number) => `Fetched ${curr} / ${total} comments...`,
    analyzing: 'Analyzing project info...',
    localMode: 'Fast Local Parsing Mode',
    noProjects: 'No projects found',
    noProjectsSub: 'Data source might be inaccessible.',
    backToList: 'Back to List',
    visitProject: 'Visit Project',
    viewDiscussion: 'View Discussion',
    websitePreview: 'Website Preview',
    previewNote: '*Some websites may not load due to security policies (X-Frame-Options). Click "Visit Project" to open directly.',
    noPreview: 'No preview available',
    filterByTag: 'Filter by Tag',
    viewDetails: 'View Details',
    view: 'View',
    footerShowing: (current: number, total: number) => `Showing ${current} of ${total} projects`,
    footerSource: 'Data sourced from',
    viewModeSnapshot: 'Snapshot',
    viewModeLive: 'Live Preview'
  }
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    name: 'Daylight Goals',
    description: 'Tracks sunlight exposure to improve sleep quality. Solves SAD/sleep issues. Monetized via $4.99/mo subscription.',
    description_zh: '追踪日光暴露以改善睡眠质量。解决季节性情绪失调问题。通过 $4.99/月订阅盈利。',
    fullDescription: 'Daylight Goals helps users track sunlight exposure to better regulate circadian rhythms. It addresses poor sleep and mood issues caused by lack of light. Revenue comes from premium subscriptions for advanced analytics.',
    fullDescription_zh: 'Daylight Goals 帮助用户追踪日光暴露量，以更好地调节昼夜节律。它解决了因光照不足导致的睡眠质量差和情绪问题。收入来自高级分析功能的付费订阅。',
    revenue: '$500',
    url: 'https://daylightgoals.com',
    hnUrl: 'https://news.ycombinator.com/item?id=46307973',
    tags: [Category.APP, Category.IOS, Category.HEALTH],
    author: 'jclardy',
    year: '2025',
    imageUrl: 'https://picsum.photos/800/600?random=1',
    previewColor: '#FF9500' // Orange like screenshot
  },
  {
    id: '2',
    name: 'Mentorbook',
    description: 'Connects mentors with mentees for career growth. Solves networking fragmentation. Monetized via 10% commission on sessions.',
    description_zh: '连接导师和学员以促进职业发展。解决人脉分散问题。通过每场会议 10% 佣金盈利。',
    fullDescription: 'Mentorbook creates a marketplace for professional mentorship, solving the difficulty of finding qualified mentors. It monetizes by taking a transaction fee on booked sessions.',
    fullDescription_zh: 'Mentorbook 创建了一个专业指导市场，解决了寻找合格导师的难题。它通过在预约会议中收取交易费来获利。',
    revenue: '$600',
    url: 'https://mentorbook.com',
    hnUrl: 'https://news.ycombinator.com/item?id=46307973',
    tags: [Category.SAAS, Category.TOOL, Category.EDUCATION],
    author: 'mentor_dev',
    year: '2024',
    imageUrl: 'https://picsum.photos/800/600?random=2',
    previewColor: '#FFFFFF'
  },
  {
    id: '3',
    name: 'Universymbols',
    description: 'Universal icon library for cross-lang UI. Solves localization costs. Monetized via $29 one-time icon pack sales.',
    description_zh: '用于跨语言 UI 的通用图标库。解决本地化成本高的问题。通过 $29 一次性图标包销售盈利。',
    fullDescription: 'Universymbols offers a standard set of icons understood globally, reducing the need for text translation in apps. It generates revenue through one-time purchases of vector packs.',
    fullDescription_zh: 'Universymbols 提供一套全球通用的图标，减少了应用程序中的文本翻译需求。它通过一次性购买矢量图标包产生收入。',
    revenue: '$550',
    url: 'https://universymbols.com',
    hnUrl: 'https://news.ycombinator.com/item?id=46307973',
    tags: [Category.APP, Category.DESIGN],
    author: 'uni_creator',
    year: '2025',
    imageUrl: 'https://picsum.photos/800/600?random=3',
    previewColor: '#E5E7EB' // Grey like screenshot
  },
  {
    id: '4',
    name: 'IronCalc',
    description: 'High-perf Rust spreadsheet engine. Solves slow web calc issues. Monetized via dual-licensing for enterprise.',
    description_zh: '高性能 Rust 电子表格引擎。解决 Web 计算慢的问题。通过企业双重许可盈利。',
    fullDescription: 'IronCalc provides a developer-friendly spreadsheet engine that is faster than JS alternatives. It solves performance bottlenecks in data apps. Monetized through enterprise support and licensing.',
    fullDescription_zh: 'IronCalc 提供了一个对开发者友好的电子表格引擎，比 JS 替代方案更快。它解决了数据应用中的性能瓶颈。通过企业支持和许可获利。',
    revenue: '$800',
    url: 'https://ironcalc.com',
    hnUrl: 'https://news.ycombinator.com/item?id=46307973',
    tags: [Category.DEVTOOLS, Category.TOOL, Category.DATABASE],
    author: 'rust_fan',
    year: '2025',
    imageUrl: 'https://picsum.photos/800/600?random=4',
    previewColor: '#FFF7ED'
  },
  {
    id: '5',
    name: 'Soundreads',
    description: 'Curated audiobook subscription. Solves "too many bad books" problem. Monetized via $15/mo subscription.',
    description_zh: '精选有声读物订阅。解决“烂书太多”的问题。通过 $15/月订阅盈利。',
    fullDescription: 'Soundreads curates only high-rated audiobooks, saving users time searching. It solves the paradox of choice in media. Revenue comes from monthly subscriber fees.',
    fullDescription_zh: 'Soundreads 只精选高评分的有声读物，节省用户搜索时间。它解决了媒体选择困难的问题。收入来自每月的订阅费。',
    revenue: '$1200',
    url: 'https://soundreads.com',
    hnUrl: 'https://news.ycombinator.com/item?id=46307973',
    tags: [Category.MEDIA, Category.WEBSITE],
    author: 'audio_lover',
    year: '2024',
    imageUrl: 'https://picsum.photos/800/600?random=5',
    previewColor: '#F3F4F6'
  }
];

export const CATEGORY_COUNTS: Record<string, number> = {};